# Generated by Django 2.0.3 on 2018-03-25 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 19, 26, 34, 692958, tzinfo=utc)),
        ),
    ]
